version: "3"

services:
    frontend:
        command: yarn start
        build: ./frontend
        ports:
            - "8000:8000"
        volumes:
            - "./frontend:/app"
            - "./backend_storage:/storage_mounted_for_testing"
    backend:
        volumes:
            - "./backend:/app"
            - "./pg_data:/backup"
            - "./backend_storage:/storage"
    db:
        volumes:
            - "./pg_data/db:/var/lib/postgresql/data"
    mailcatcher:
        image: rordi/docker-mailcatcher
        container_name: mailcatcher
        ports:
            - 1080:1080
            - 1025:1025
