version: '3'

services:
  db:
    image: 'postgres:10.5-alpine'
    volumes:
      - './tmp/db:/var/lib/postgresql/data'
    env_file:
      - '.env'
  tapp:
    depends_on:
      - 'db'
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    env_file:
      - '.env'
  frontend:
    build: ./frontend
    ports:
      - '8000:8000'
    volumes:
      - '.:/frontend'
