version: '3'

services:
  db:
    image: 'postgres:10.5-alpine'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  api:
    depends_on:
      - 'db'
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    build: ./api
    ports:
      - '3023:3000'
    environment:
      RAILS_ENV: ${RAILS_ENV}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_SERVE_STATIC_FILES: ${RAILS_SERVE_STATIC_FILES}
      RAILS_LOG_TO_STDOUT: ${RAILS_LOG_TO_STDOUT}

